export const TRANSACTIONS_HAVE_ERROR = 'TRANSACTIONS_HAVE_ERROR';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_STATUS = 'UPDATE_STATUS';
export const SELECT_TRANSACTIONS = 'SELECT_TRANSACTIONS';
export const UPDATE_SELECT_TRANSACTIONS = 'UPDATE_SELECT_TRANSACTIONS';